apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: axispay-standard
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
