apiVersion: v1
kind: PersistentVolume
metadata:
  name: axispay-ledger-archive
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: axispay-manual
  hostPath:
    path: /mnt/axispay/ledger-archive
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - axispay-m02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ledger-archive
  namespace: axispay-core
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: axispay-manual
  resources:
    requests:
      storage: 1Gi
