apiVersion: v1
kind: Service
metadata:
  name: loadgen
  namespace: axispay-ops
  labels:
    app.kubernetes.io/name: loadgen
    app.kubernetes.io/instance: axispay
    app.kubernetes.io/component: ops
    app.kubernetes.io/part-of: axispay
    axispay.io/day-introduced: "2"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loadgen
    app.kubernetes.io/instance: axispay
  ports:
    - name: http
      port: 8080
      targetPort: http
