apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axispay-edge
  namespace: axispay-edge
spec:
  namespaceSelector:
    matchNames:
    - axispay-edge
  selector:
    matchLabels:
      app.kubernetes.io/part-of: axispay
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels:
      - __name__
      regex: python_gc_.*|process_.*
      action: drop
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axispay-core
  namespace: axispay-core
spec:
  namespaceSelector:
    matchNames:
    - axispay-core
  selector:
    matchLabels:
      app.kubernetes.io/part-of: axispay
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels:
      - __name__
      regex: python_gc_.*|process_.*
      action: drop
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axispay-async
  namespace: axispay-async
spec:
  namespaceSelector:
    matchNames:
    - axispay-async
  selector:
    matchLabels:
      app.kubernetes.io/part-of: axispay
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels:
      - __name__
      regex: python_gc_.*|process_.*
      action: drop
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: axispay-ops
  namespace: axispay-ops
spec:
  namespaceSelector:
    matchNames:
    - axispay-ops
  selector:
    matchLabels:
      app.kubernetes.io/part-of: axispay
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
