apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: axispay-routing
  namespace: axispay-observability
spec:
  route:
    receiver: platform-default
    groupBy:
    - alertname
    - namespace
    - severity
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
    - receiver: payments-oncall
      matchers:
      - name: severity
        value: critical
      - name: team
        value: payments
      groupWait: 10s
      repeatInterval: 1h
      continue: false
    - receiver: finance-ops
      matchers:
      - name: team
        value: finance-ops
      repeatInterval: 12h
    - receiver: risk-team
      matchers:
      - name: team
        value: risk
      repeatInterval: 12h
    - receiver: platform-oncall
      matchers:
      - name: severity
        value: critical
      repeatInterval: 1h
  inhibitRules:
  - sourceMatch:
    - name: alertname
      value: AxisPayServiceNoReadyEndpoints
    targetMatch:
    - name: alertname
      value: AxisPayPaymentErrorRateHigh
    equal:
    - namespace
  - sourceMatch:
    - name: alertname
      value: AxisPayServiceNoReadyEndpoints
    targetMatch:
    - name: alertname
      value: AxisPayPaymentLatencyHigh
    equal:
    - namespace
  - sourceMatch:
    - name: alertname
      value: AxisPayPodCrashLooping
    targetMatch:
    - name: alertname
      value: AxisPayContainerOOMKilled
    equal:
    - namespace
    - pod
  - sourceMatch:
    - name: severity
      value: critical
    targetMatch:
    - name: severity
      value: warning
    equal:
    - alertname
    - namespace
  receivers:
  - name: platform-default
    webhookConfigs:
    - url: http://alert-sink.axispay-observability.svc.cluster.local:8080/alerts/platform
      sendResolved: true
  - name: platform-oncall
    webhookConfigs:
    - url: http://alert-sink.axispay-observability.svc.cluster.local:8080/alerts/platform-oncall
      sendResolved: true
  - name: payments-oncall
    webhookConfigs:
    - url: http://alert-sink.axispay-observability.svc.cluster.local:8080/alerts/payments
      sendResolved: true
  - name: finance-ops
    webhookConfigs:
    - url: http://alert-sink.axispay-observability.svc.cluster.local:8080/alerts/finance
      sendResolved: true
  - name: risk-team
    webhookConfigs:
    - url: http://alert-sink.axispay-observability.svc.cluster.local:8080/alerts/risk
      sendResolved: true
