apiVersion: v1
kind: ConfigMap
metadata:
  name: axispay-platform-config
  namespace: axispay-core
data:
  ENVIRONMENT: training
  LOG_LEVEL: info
  DEFAULT_CURRENCY: ZAR
  SUPPORTED_CURRENCIES: ZAR,USD,EUR,GBP,NGN,KES,BWP
  DOWNSTREAM_TIMEOUT_SECONDS: '5.0'
  AUTH_SERVICE_URL: http://auth-service.axispay-edge.svc.cluster.local:8080
  MERCHANT_SERVICE_URL: http://merchant-service.axispay-core.svc.cluster.local:8080
  PAYMENT_SERVICE_URL: http://payment-service.axispay-core.svc.cluster.local:8080
  CUSTOMER_SERVICE_URL: http://customer-service.axispay-core.svc.cluster.local:8080
  FRAUD_SERVICE_URL: http://fraud-service.axispay-core.svc.cluster.local:8080
  ROUTING_SERVICE_URL: http://routing-service.axispay-core.svc.cluster.local:8080
  LEDGER_SERVICE_URL: http://ledger-service.axispay-core.svc.cluster.local:8080
  POSTGRES_HOST: postgres-0.postgres.axispay-data.svc.cluster.local
  POSTGRES_PORT: '5432'
  POSTGRES_DB: axispay
  REDIS_HOST: redis-0.redis.axispay-data.svc.cluster.local
  REDIS_PORT: '6379'
  RABBITMQ_HOST: rabbitmq-0.rabbitmq.axispay-data.svc.cluster.local
  RABBITMQ_PORT: '5672'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: axispay-fraud-rules
  namespace: axispay-core
data:
  fraud-rules.yaml: "velocity:\n  window_seconds: 300\n  thresholds:\n    - { attempts:\
    \ 3,  score: 8 }\n    - { attempts: 5,  score: 22 }\n    - { attempts: 9,  score:\
    \ 45 }\ndecision:\n  review_at: 45\n  decline_at: 75\namount_deviation:\n  above_typical_x3:\
    \ 10\n  above_typical_x6: 25\ngeography:\n  cross_border_penalty: 12\n"
