apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: axispay-core
spec:
  template:
    spec:
      tolerations:
      - key: axispay.io/pci-zone
        operator: Equal
        value: cde
        effect: NoSchedule
      nodeSelector:
        axispay.io/pci-zone: cde
