apiVersion: v1
kind: Namespace
metadata:
  name: axispay-core
---
apiVersion: v1
kind: Namespace
metadata:
  name: axispay-edge
---
apiVersion: v1
kind: Namespace
metadata:
  name: axispay-async
---
apiVersion: v1
kind: Namespace
metadata:
  name: axispay-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: axispay-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: axispay-observability
