apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-gateway
  namespace: axispay-edge
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: axispay-edge
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: axispay-core
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: axispay-core-workload
  namespace: axispay-core
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: axispay-async-workload
  namespace: axispay-async
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-agent
  namespace: axispay-ops
automountServiceAccountToken: true
